# Generated by Django 4.2.16 on 2026-04-08 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_franchiseagreement_remove_leadmodel_assigned_to_and_more'),
        ('account', '0005_alter_myuser_options_alter_myuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short personal bio — not visible to customers.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='calendly_url',
            field=models.URLField(blank=True, help_text='Calendly or Cal.com booking link.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='direct_email',
            field=models.EmailField(blank=True, help_text='Work email if different from login email.', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notify_new_lead_email',
            field=models.BooleanField(default=True, help_text='Email me when a new lead is assigned.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notify_new_lead_sms',
            field=models.BooleanField(default=False, help_text='SMS me when a new lead is assigned.'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='base_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual base salary in USD (if applicable).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Commission percentage on closed deals (e.g. 5.00 = 5%).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='draw_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly draw against commission (if applicable).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='end_date',
            field=models.DateField(blank=True, help_text='Leave blank if currently active.', null=True),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Who this person reports to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='account.salesperson'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='sales_point',
            field=models.ForeignKey(blank=True, help_text='Primary location this person is assigned to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salespeople', to='home.salespoint'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='territory_notes',
            field=models.TextField(blank=True, help_text='For territory managers: description of their oversight area.'),
        ),
    ]
