# Generated by Django 4.2.16 on 2026-04-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_add_estimate_models'),
        ('account', '0006_alter_profile_bio_alter_profile_calendly_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='extra_sales_points',
            field=models.ManyToManyField(blank=True, help_text='Additional locations this person manages.', related_name='extra_salespeople', to='home.salespoint'),
        ),
    ]
