# Generated by Django 4.2.16 on 2026-05-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_update_role_project_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanager',
            name='role',
            field=models.CharField(choices=[('project_manager', 'Project Manager'), ('location_manager', 'Multiple Locations Manager'), ('territory_manager', 'Territory Manager')], default='project_manager', max_length=30),
        ),
    ]
