# Generated by Django 4.2.16 on 2026-05-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_projectmanager_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stable identifier referenced in code; lower_snake_case.', max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('allows_multiple_locations', models.BooleanField(default=False, help_text='If on, this role can be assigned more than one sales point.')),
                ('sees_all_locations', models.BooleanField(default=False, help_text='If on, members of this role see leads from every active sales point, regardless of assignment.')),
                ('is_protected', models.BooleanField(default=False, help_text='Protected roles are referenced by code elsewhere in the app and cannot be deleted.')),
                ('order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='role',
            field=models.CharField(default='project_manager', max_length=40),
        ),
    ]
