# Generated by Django 4.2.16 on 2026-04-21 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_add_gallery_thumbnail_mobile'),
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sales_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_customers', to='home.salespoint'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='sales_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_estimates', to='home.salespoint'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_invoices', to='home.salespoint'),
        ),
        migrations.AddField(
            model_name='project',
            name='sales_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_projects', to='home.salespoint'),
        ),
    ]
