# Generated by Django 4.2.16 on 2026-04-21 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_add_gallery_thumbnail_mobile'),
        ('panel', '0002_customer_sales_point_estimate_sales_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPointPartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='sales_point',
            field=models.ForeignKey(blank=True, help_text='NULL = global part, set = local to this location.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='home.salespoint'),
        ),
        migrations.AddField(
            model_name='partcategory',
            name='sales_point',
            field=models.ForeignKey(blank=True, help_text='NULL = global category, set = local to this location.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_categories', to='home.salespoint'),
        ),
        migrations.AlterField(
            model_name='partcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='partcategory',
            constraint=models.UniqueConstraint(fields=('name', 'sales_point'), name='unique_category_per_location'),
        ),
        migrations.AddConstraint(
            model_name='partcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('sales_point__isnull', True)), fields=('name',), name='unique_global_category_name'),
        ),
        migrations.AddField(
            model_name='salespointpartcategory',
            name='category',
            field=models.ForeignKey(limit_choices_to={'sales_point__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='panel.partcategory'),
        ),
        migrations.AddField(
            model_name='salespointpartcategory',
            name='sales_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_part_categories', to='home.salespoint'),
        ),
        migrations.AlterUniqueTogether(
            name='salespointpartcategory',
            unique_together={('sales_point', 'category')},
        ),
    ]
