# Generated by Django 4.2.16 on 2026-04-21 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_add_gallery_thumbnail_mobile'),
        ('panel', '0003_salespointpartcategory_part_sales_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPointUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='sales_point',
            field=models.ForeignKey(blank=True, help_text='NULL = global unit, set = local to this location.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='home.salespoint'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('name', 'sales_point'), name='unique_unit_per_location'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(condition=models.Q(('sales_point__isnull', True)), fields=('name',), name='unique_global_unit_name'),
        ),
        migrations.AddField(
            model_name='salespointunit',
            name='sales_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_units', to='home.salespoint'),
        ),
        migrations.AddField(
            model_name='salespointunit',
            name='unit',
            field=models.ForeignKey(limit_choices_to={'sales_point__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='panel.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='salespointunit',
            unique_together={('sales_point', 'unit')},
        ),
    ]
