# Generated by Django 4.2.16 on 2026-04-21 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_add_gallery_thumbnail_mobile'),
        ('panel', '0004_salespointunit_unit_is_active_unit_sales_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPointPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(limit_choices_to={'sales_point__isnull': True}, on_delete=django.db.models.deletion.CASCADE, to='panel.part')),
                ('sales_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_parts', to='home.salespoint')),
            ],
            options={
                'unique_together': {('sales_point', 'part')},
            },
        ),
    ]
