# Generated by Django 4.2.16 on 2026-04-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_salespointpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespointpart',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override the global price for this location. Leave blank to use global price.', max_digits=10, null=True),
        ),
    ]
