# Generated by Django 4.2.16 on 2026-04-21 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_salespointpart_custom_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespointpart',
            name='custom_unit',
            field=models.ForeignKey(blank=True, help_text='Override the unit for this location.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.unit'),
        ),
        migrations.AlterField(
            model_name='salespointpart',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
