# Generated by Django 4.2.16 on 2026-04-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_salespointpart_custom_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Only used for local parts. Global parts have no price — each location sets their own.', max_digits=10),
        ),
    ]
