# Generated by Django 4.2.16 on 2026-05-02 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_leadstatus_is_quick_filter'),
        ('panel', '0008_alter_part_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_estimates', to='home.leadmodel'),
        ),
    ]
