# Generated by Django 4.2.16 on 2026-05-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_estimatetemplate_estimatetemplateitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partcategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Part categories'},
        ),
        migrations.AddField(
            model_name='partcategory',
            name='order',
            field=models.PositiveIntegerField(default=100, help_text='Lower numbers appear first. Use this to control display order.'),
        ),
    ]
