# Generated by Django 4.2.16 on 2026-05-11 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0020_leadmodel_appointment_at'),
        ('panel', '0014_googlecalendarcredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unit_label', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sales_point', models.ForeignKey(blank=True, help_text='NULL = global package, set = local to this location.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimate_packages', to='home.salespoint')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
