# Generated by Django 4.2.16 on 2026-05-11 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_estimatepackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimatepackage',
            name='price',
        ),
        migrations.RemoveField(
            model_name='estimatepackage',
            name='unit_label',
        ),
        migrations.AddField(
            model_name='estimatepackage',
            name='markup_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Markup percentage applied on top of unit_price.', max_digits=6),
        ),
        migrations.AddField(
            model_name='estimatepackage',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Unit (e.g. sq ft, lump sum). Optional.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.unit'),
        ),
        migrations.AddField(
            model_name='estimatepackage',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit, before markup.', max_digits=10),
        ),
    ]
