# Generated by Django 4.2.16 on 2026-05-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_remove_estimatepackage_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimatepackage',
            name='markup_pct',
        ),
        migrations.AddField(
            model_name='estimate',
            name='labor_markup_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='estimate',
            name='material_markup_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='estimate',
            name='sub_markup_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='cost_type',
            field=models.CharField(choices=[('material', 'Material'), ('labor', 'Labor'), ('sub', 'Subcontractor')], default='material', max_length=10),
        ),
        migrations.AddField(
            model_name='estimatepackage',
            name='cost_type',
            field=models.CharField(choices=[('material', 'Material'), ('labor', 'Labor'), ('sub', 'Subcontractor')], default='material', max_length=10),
        ),
        migrations.AddField(
            model_name='part',
            name='cost_type',
            field=models.CharField(choices=[('material', 'Material'), ('labor', 'Labor'), ('sub', 'Subcontractor')], default='material', max_length=10),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Marked-up subtotal (cost + markup), customer-facing.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='estimatepackage',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per unit. Markup is applied at the estimate level by cost type.', max_digits=10),
        ),
    ]
