# Generated by Django 4.2.16 on 2026-05-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0017_remove_estimatepackage_markup_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateitem',
            name='markup_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per-item markup % override. 0 = use estimate-level markup for this cost_type.', max_digits=6),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='multiplier',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Per-item multiplier (e.g. labor rate for labor rows).', max_digits=10),
        ),
    ]
