# Generated by Django 4.2.16 on 2026-07-28 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0018_estimateitem_markup_pct_estimateitem_multiplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, help_text='Expense/income category, e.g. Materials, Labor, Fuel.', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payee',
            field=models.CharField(blank=True, help_text='Vendor/payee name for expenses when no customer applies.', max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('check', 'Check'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='panel.project'),
        ),
    ]
