# Generated by Django 4.2.16 on 2026-07-28 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_leadmodel_appointment_at'),
        ('panel', '0019_alter_transaction_options_transaction_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('institution', models.CharField(blank=True, max_length=120)),
                ('mask', models.CharField(blank=True, help_text='Last digits, e.g. 4021.', max_length=8)),
                ('color', models.CharField(default='#2563eb', max_length=9)),
                ('bank_balance', models.DecimalField(decimal_places=2, default=0, help_text='Balance reported by the bank (the pencil-editable figure).', max_digits=14)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Ledger balance before any posted lines.', max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='home.salespoint')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bank_description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('excluded', 'Excluded')], default='pending', max_length=10)),
                ('payee', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('attachment_count', models.PositiveIntegerField(default=0)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='panel.bankaccount')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_lines', to='panel.customer')),
                ('matched_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_matches', to='panel.invoice')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_lines', to='panel.project')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['account', 'status', '-date'], name='panel_bankt_account_6c8499_idx')],
            },
        ),
    ]
