# Generated by Django 4.2.16 on 2026-07-28 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0020_bankaccount_banktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='plaid_account_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='bank_pending',
            field=models.BooleanField(default=False, help_text='True while the bank itself still marks it pending.'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='plaid_txn_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='PlaidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100, unique=True)),
                ('access_token', models.CharField(max_length=200)),
                ('institution_id', models.CharField(blank=True, max_length=100)),
                ('institution_name', models.CharField(blank=True, max_length=200)),
                ('cursor', models.CharField(blank=True, max_length=256)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plaid_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='plaid_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='panel.plaiditem'),
        ),
    ]
