# Generated by Django 4.2.16 on 2026-08-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0021_bankaccount_plaid_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plaiditem',
            name='needs_reauth',
            field=models.BooleanField(default=False),
        ),
    ]
