# Generated by Django 4.2.16 on 2026-04-05 04:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import home.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Optional gallery cover image used on the galleries page.', null=True, upload_to=home.models.gallery_cover_upload_to)),
                ('page_title', models.CharField(blank=True, max_length=255)),
                ('intro_text', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Galleries',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SalesPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('local_phone', models.CharField(blank=True, max_length=30)),
                ('local_email', models.EmailField(blank=True, max_length=254)),
                ('lead_notification_email', models.EmailField(blank=True, max_length=254)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('reply_to_email', models.EmailField(blank=True, max_length=254)),
                ('assigned_salesperson', models.CharField(blank=True, max_length=120)),
                ('intro_text', models.TextField(blank=True)),
                ('seo_body', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('sales_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='home.salespoint')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='testimonials/')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('message', models.TextField()),
                ('source_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VideoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('video', models.FileField(upload_to='video_reviews/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_reviews/thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('service_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_codes', to='home.servicecity')),
            ],
            options={
                'verbose_name': 'Zip Code',
                'verbose_name_plural': 'Zip Codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LeadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=10)),
                ('assigned_to', models.CharField(blank=True, max_length=120)),
                ('consultation_types', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('garage_flooring', 'Garage Flooring'), ('garage_cabinets', 'Garage Cabinets'), ('garage_slatwall', 'Garage Slatwall'), ('storage_racks', 'Storage Racks'), ('garage_door', 'Garage Door'), ('garage_makeover', 'Garage Makeover'), ('garage_conversion', 'Garage Conversion'), ('car_lift', 'Car Lift')], max_length=116)),
                ('message', models.TextField(blank=True)),
                ('source_page', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('appointment_set', 'Appointment Set'), ('quoted', 'Quoted'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='new', max_length=30)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('sales_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='home.salespoint')),
                ('service_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='home.servicecity')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lead_attachments/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='home.leadmodel')),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('section_heading', models.CharField(blank=True, max_length=255)),
                ('text_before', models.TextField(blank=True)),
                ('text_after', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('image', 'Photo'), ('video', 'Video')], default='image', max_length=10)),
                ('file', models.FileField(upload_to=home.models.gallery_media_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'mp4', 'mov', 'm4v', 'webm', 'ogg'])])),
                ('thumbnail', models.ImageField(blank=True, help_text='Required for videos. Optional for photos.', null=True, upload_to=home.models.gallery_thumb_upload_to)),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.gallery')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='sales_points',
            field=models.ManyToManyField(blank=True, related_name='galleries', to='home.salespoint'),
        ),
        migrations.AddConstraint(
            model_name='servicecity',
            constraint=models.UniqueConstraint(fields=('sales_point', 'name', 'state'), name='unique_salespoint_city_state'),
        ),
    ]
