# Generated by Django 4.2 on 2026-03-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='intro_text',
            field=models.TextField(blank=True, help_text='Optional intro text shown near the top of the gallery detail page.'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='page_title',
            field=models.CharField(blank=True, help_text='Optional custom title for the gallery detail page.', max_length=255),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='section_heading',
            field=models.CharField(blank=True, help_text='Optional heading shown before this photo or video.', max_length=255),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='text_after',
            field=models.TextField(blank=True, help_text='Optional text shown after this photo or video.'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='text_before',
            field=models.TextField(blank=True, help_text='Optional text shown before this photo or video.'),
        ),
    ]
