# Generated by Django 4.2.16 on 2026-04-05 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPointWorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('is_open', models.BooleanField(default=True)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('sales_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='home.salespoint')),
            ],
            options={
                'verbose_name': 'Working Hour',
                'verbose_name_plural': 'Working Hours',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='salespointworkinghour',
            constraint=models.UniqueConstraint(fields=('sales_point', 'day'), name='unique_salespoint_day'),
        ),
    ]
