# Generated by Django 4.2.16 on 2026-04-05 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_salespointworkinghour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='leadmodel',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadmodel',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
