# Generated by Django 4.2.16 on 2026-04-08 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_leadmodel_name_leadmodel_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchisee_legal_name', models.CharField(max_length=200)),
                ('franchisee_contact_name', models.CharField(blank=True, max_length=120)),
                ('franchisee_email', models.EmailField(blank=True, max_length=254)),
                ('franchisee_phone', models.CharField(blank=True, max_length=30)),
                ('upfront_fee', models.DecimalField(blank=True, decimal_places=2, help_text='One-time franchise fee in USD', max_digits=10, null=True)),
                ('royalty_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly royalty as % of gross revenue', max_digits=5, null=True)),
                ('marketing_fee_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Marketing fund contribution as % of gross revenue', max_digits=5, null=True)),
                ('territory_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='pending', max_length=20)),
                ('agreement_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('agreement_document', models.FileField(blank=True, help_text='Signed franchise agreement PDF', null=True, upload_to='franchise/agreements/')),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Franchise Agreement',
                'verbose_name_plural': 'Franchise Agreements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='leadmodel',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='salespoint',
            name='location_type',
            field=models.CharField(choices=[('company', 'Company-Owned'), ('franchise', 'Franchise'), ('rental', 'Rental / Licensed')], default='company', max_length=20),
        ),
        migrations.AddField(
            model_name='salespoint',
            name='royalty_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Royalty percentage (e.g. 6.00 for 6%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='servicecity',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='servicecity',
            constraint=models.UniqueConstraint(fields=('sales_point', 'slug'), name='unique_salespoint_city_slug'),
        ),
        migrations.AddField(
            model_name='franchiseagreement',
            name='sales_point',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='franchise_agreement', to='home.salespoint'),
        ),
    ]
