# Generated by Django 4.2.16 on 2026-04-11 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_leadactivity'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='servicecity',
            name='unique_salespoint_city_state',
        ),
        migrations.RemoveConstraint(
            model_name='servicecity',
            name='unique_salespoint_city_slug',
        ),
        migrations.AlterField(
            model_name='servicecity',
            name='sales_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='home.salespoint'),
        ),
        migrations.AlterField(
            model_name='servicecity',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddConstraint(
            model_name='servicecity',
            constraint=models.UniqueConstraint(fields=('name', 'state'), name='unique_city_state'),
        ),
    ]
