# Generated by Django 4.2.16 on 2026-04-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_servicecity_independent_from_salespoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmodel',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
