# Generated by Django 4.2.16 on 2026-04-18 14:18

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_add_estimate_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='thumbnail_mobile',
            field=models.ImageField(blank=True, help_text='Optional square thumbnail for mobile devices. Falls back to the desktop thumbnail if empty.', null=True, upload_to=home.models.gallery_cover_upload_to),
        ),
    ]
