# Generated by Django 4.2.16 on 2026-04-28 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0014_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_at', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_followups_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='home.leadmodel')),
            ],
            options={
                'verbose_name': 'Lead Follow-Up',
                'verbose_name_plural': 'Lead Follow-Ups',
                'ordering': ['remind_at'],
            },
        ),
    ]
