# Generated by Django 4.2.16 on 2026-04-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_leadfollowup'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadfollowup',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='Set when the user opens the lead detail page after the reminder fires.', null=True),
        ),
    ]
