# Generated by Django 4.2.16 on 2026-05-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_leadfollowup_acknowledged'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstatus',
            name='is_quick_filter',
            field=models.BooleanField(default=False, help_text='When enabled, this status appears as a quick filter button on the leads list page.'),
        ),
    ]
