# Generated by Django 4.2.16 on 2026-05-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_leadstatus_is_quick_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmodel',
            name='status',
            field=models.CharField(default='new', max_length=30),
        ),
    ]
