# Generated by Django 4.2.16 on 2026-05-09 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_leadmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short region code, e.g. NOR, SOU, CEN', max_length=8)),
                ('name', models.CharField(help_text="Public/marketing name, e.g. 'Northern California'", max_length=120)),
                ('internal_label', models.CharField(blank=True, help_text='Optional internal-only label.', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['state__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='USPS two-letter state code, e.g. CA, TX', max_length=2, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ZipCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=10, unique=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('county', models.CharField(blank=True, max_length=120)),
                ('coverage_type', models.CharField(choices=[('core', 'Core'), ('extended', 'Extended'), ('edge', 'Edge'), ('future', 'Future')], default='core', max_length=16)),
                ('drive_time_target', models.PositiveSmallIntegerField(blank=True, help_text='Target minutes from primary sales point. Planning value, not measured.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ZIP coverage',
                'verbose_name_plural': 'ZIP coverage',
                'ordering': ['state__code', 'region__code', 'zip_code'],
            },
        ),
        migrations.AddField(
            model_name='salespoint',
            name='base_city',
            field=models.CharField(blank=True, help_text="Operational base city, e.g. 'Santa Clara'. May differ from marketing name.", max_length=120),
        ),
        migrations.AddField(
            model_name='salespoint',
            name='code',
            field=models.CharField(blank=True, help_text='Short sales-point code unique within its region, e.g. SCL, DAL.', max_length=8),
        ),
        migrations.AddField(
            model_name='region',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='home.state'),
        ),
        migrations.AddField(
            model_name='salespoint',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_points', to='home.region'),
        ),
        migrations.AddConstraint(
            model_name='salespoint',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('region', 'code'), name='unique_sp_code_per_region'),
        ),
        migrations.AddField(
            model_name='zipcoverage',
            name='backup_sales_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_zip_coverages', to='home.salespoint'),
        ),
        migrations.AddField(
            model_name='zipcoverage',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zip_coverages', to='home.region'),
        ),
        migrations.AddField(
            model_name='zipcoverage',
            name='sales_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_zip_coverages', to='home.salespoint'),
        ),
        migrations.AddField(
            model_name='zipcoverage',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zip_coverages', to='home.state'),
        ),
        migrations.AddIndex(
            model_name='zipcoverage',
            index=models.Index(fields=['state', 'region'], name='home_zipcov_state_i_9f02c1_idx'),
        ),
        migrations.AddIndex(
            model_name='zipcoverage',
            index=models.Index(fields=['sales_point', 'coverage_type'], name='home_zipcov_sales_p_5601be_idx'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('state', 'code'), name='unique_region_per_state'),
        ),
    ]
