# Generated by Django 4.2.16 on 2026-05-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_territory'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmodel',
            name='appointment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
