# Generated by Django 4.2.16 on 2026-08-07 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0020_leadmodel_appointment_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('color', models.CharField(default='#6b7280', help_text='Hex colour for the column header, e.g. #2563eb', max_length=7)),
                ('order', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_won', models.BooleanField(default=False, help_text="Terminal 'delivered/complete' column.")),
                ('is_lost', models.BooleanField(default=False, help_text="Terminal 'cancelled/dead' column.")),
            ],
            options={
                'verbose_name': 'Cabinet stage',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='CabinetProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('source_notes', models.TextField(blank=True, help_text='Message/notes copied from the lead at send time.')),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('quoted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('linear_feet', models.DecimalField(blank=True, decimal_places=2, help_text='Total run of cabinets, in linear feet.', max_digits=7, null=True)),
                ('finish', models.CharField(blank=True, max_length=120)),
                ('measure_date', models.DateField(blank=True, null=True)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinet_projects_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinet_projects', to='home.leadmodel')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='customlux.cabinetstage')),
            ],
            options={
                'verbose_name': 'Cabinet project',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CabinetMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('can_edit', models.BooleanField(default=True, help_text='Off = read-only access to the board.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinet_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cabinet board member',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='CabinetActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='customlux.cabinetproject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinet_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cabinet activity',
                'ordering': ['-created_at'],
            },
        ),
    ]
