# Generated by Django 4.2.16 on 2026-08-07 05:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customlux', '0002_seed_stages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Percent of the pre-tax deal amount owed to Garage Lions.', max_digits=5)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sales-tax percent used to pre-fill the tax field on a new deal. Tax is always excluded from the commission base.', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CustomLux settings',
                'verbose_name_plural': 'CustomLux settings',
            },
        ),
        migrations.AddField(
            model_name='cabinetproject',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Commission rate for this deal (%)'),
        ),
        migrations.AddField(
            model_name='cabinetproject',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sales tax included in the total'),
        ),
        migrations.AlterField(
            model_name='cabinetproject',
            name='quoted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Deal total (incl. tax)'),
        ),
    ]
