# Generated by Django 4.2.16 on 2026-08-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customlux', '0003_cabinetsettings_cabinetproject_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetsettings',
            name='commission_basis',
            field=models.CharField(choices=[('markup', "Markup added on top of CustomLux's price"), ('share', 'Share taken out of the deal total')], default='markup', max_length=10),
        ),
    ]
