# Generated by Django 4.2.16 on 2026-08-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customlux', '0004_cabinetsettings_commission_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetproject',
            name='source_notes',
            field=models.TextField(blank=True),
        ),
    ]
