# Generated by Django 4.2.16 on 2026-08-07 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customlux', '0005_alter_cabinetproject_source_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinet_todos_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='customlux.cabinetproject')),
            ],
            options={
                'verbose_name': 'Cabinet to-do',
                'ordering': ['is_completed', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CabinetEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='customlux_estimates/%Y/%m/')),
                ('label', models.CharField(blank=True, help_text='Optional — e.g. “Revised after site visit”.', max_length=140)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='customlux.cabinetproject')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinet_estimates_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cabinet estimate file',
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
