# Generated by Django 4.2.16 on 2026-08-07 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customlux', '0006_cabinettodo_cabinetestimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_on', models.DateField()),
                ('method', models.CharField(blank=True, choices=[('', '—'), ('check', 'Check'), ('zelle', 'Zelle'), ('transfer', 'Bank transfer'), ('cash', 'Cash'), ('card', 'Card'), ('other', 'Other')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Cheque number, transfer ref…', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customlux.cabinetproject')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinet_payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission payment',
                'ordering': ['-received_on', '-id'],
            },
        ),
    ]
