# Generated by Django 4.2.16 on 2026-08-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customlux', '0007_cabinetpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetpayment',
            name='direction',
            field=models.CharField(choices=[('in', 'Received from CustomLux'), ('out', 'Sent to CustomLux')], default='in', max_length=4),
        ),
        migrations.AddField(
            model_name='cabinetproject',
            name='collected_by',
            field=models.CharField(blank=True, choices=[('', 'Board default'), ('customlux', 'CustomLux collects from the customer'), ('garagelions', 'Garage Lions collects from the customer')], max_length=20, verbose_name='Who the customer pays'),
        ),
        migrations.AddField(
            model_name='cabinetsettings',
            name='default_collected_by',
            field=models.CharField(choices=[('customlux', 'CustomLux collects from the customer'), ('garagelions', 'Garage Lions collects from the customer')], default='customlux', max_length=20),
        ),
    ]
