# Generated by Django 4.2.16 on 2026-08-07 06:56

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customlux', '0008_cabinetpayment_direction_cabinetproject_collected_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetproject',
            name='deposit_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Deposit %'),
        ),
        migrations.AddField(
            model_name='cabinetsettings',
            name='default_deposit_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Down payment percent used to pre-fill a new deal.', max_digits=5),
        ),
        migrations.CreateModel(
            name='CabinetCustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_on', models.DateField()),
                ('is_deposit', models.BooleanField(default=False, verbose_name='This is the deposit / down payment')),
                ('method', models.CharField(blank=True, choices=[('', '—'), ('check', 'Check'), ('zelle', 'Zelle'), ('transfer', 'Bank transfer'), ('cash', 'Cash'), ('card', 'Card'), ('other', 'Other')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payments', to='customlux.cabinetproject')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinet_customer_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer payment',
                'ordering': ['-received_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CabinetChangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive to add, negative to reduce.', max_digits=10)),
                ('dated', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinet_changes_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_orders', to='customlux.cabinetproject')),
            ],
            options={
                'verbose_name': 'Change order',
                'ordering': ['dated', 'id'],
            },
        ),
    ]
