# Generated by Django 4.2.16 on 2026-08-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customlux', '0009_cabinetproject_deposit_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetproject',
            name='linear_feet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
