# Generated by Django 4.2.16 on 2026-08-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customlux', '0010_alter_cabinetproject_linear_feet'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetcustomerpayment',
            name='deposited_by',
            field=models.CharField(blank=True, choices=[('customlux', 'CustomLux deposited money'), ('garagelions', 'Garage Lions deposited money')], max_length=20, verbose_name='Who deposited this money'),
        ),
    ]
