# Generated by Django 4.2.16 on 2026-08-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customlux', '0011_cabinetcustomerpayment_deposited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetpayment',
            name='direction',
            field=models.CharField(choices=[('in', 'CustomLux sent money to Garage Lions'), ('out', 'Garage Lions sent money to CustomLux')], default='in', max_length=4),
        ),
    ]
