# Generated by Django 4.2.16 on 2026-08-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customlux', '0012_alter_cabinetpayment_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetproject',
            name='online_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Online transaction fee included in the total'),
        ),
    ]
