# Generated by Django 4.2.16 on 2026-08-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customlux', '0013_cabinetproject_online_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetmember',
            name='invite_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cabinetmember',
            name='login_created',
            field=models.BooleanField(default=False),
        ),
    ]
