# Generated by Django 4.2.16 on 2026-08-11 02:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customlux', '0015_cabinetproject_tax_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetproject',
            name='tax_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Sales tax %'),
        ),
        migrations.AlterField(
            model_name='cabinetsettings',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text="Sales-tax percent applied to any deal that doesn't set its own. The tax is added to the deal price; it never enters the commission base.", max_digits=7),
        ),
    ]
